kind: pipeline
type: docker
name: test

steps:
  - name: Test Ruby
    image: ruby:2.7.3
    commands:
      - gem install bundler -v 1.3.6
      - gem uninstall bundler --version '>1.3.6'
      - bundle -v
      - bundle install
      - bundle exec rake
